name: "🐛 Bug Report"
description: Create a new ticket for a bug in excelerate.
title: "🐛 [BUG] - <title>"
labels:
  - "bug"
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
          <img src="https://github.com/AmeliaES/excelerate/blob/main/man/figures/logo.png" alt="excelerate Logo">
          <br>
          <em>—<a href="https://ameliaes.github.io/excelerate/">excelerate documentation</a>.</em>
        </p>
  - type: checkboxes
    id: checks
    attributes:
      label: "Before Submitting"
      description: Please confirm the following to help us process your issue efficiently.
      options:
        - label: I have checked the documentation and existing issues.
          required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please provide a clear and concise description of the bug.
    validations:
      required: true
  - type: input
    id: reprod-url
    attributes:
      label: "Reproduction URL"
      description: "If you’ve forked excelerate, provide a GitHub URL or repository link to reproduce the issue."
      placeholder: "Hint: Optional, but it helps us resolve the issue faster. Leave empty if not applicable."
    validations:
      required: false
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction Steps"
      description: "List the steps to reproduce the bug. The more detailed, the better!"
      value: |
        1. Go to '...'
        2. Run '....'
        3. Observe '....'
      render: r
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### Environment Information"
  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: What operating system were you using when the bug occurred?
      options:
        - "Windows"
        - "Linux"
        - "Mac"
        - "Other"
  - type: input
    id: other-os
    attributes:
      label: "Other Operating System"
      description: "Only fill this if you selected 'Other' in the Operating System dropdown."
      placeholder: "e.g., Ubuntu 20.04"
    validations:
      required: false
  - type: input
    id: r-version
    attributes:
      label: "R Version"
      description: What version of R are you using? Run 'R --version' to check.
      placeholder: "e.g., 4.2.0"
    validations:
      required: true
  - type: input
    id: excelerate-version
    attributes:
      label: "excelerate Version"
      description: What version of excelerate are you using? For R package, run 'packageVersion(\"excelerate\")' to check."
      placeholder: "e.g., 0.1.0"
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: "Additional Information"
      description: "In case none of the above options fit your case, please provide additional information."
      placeholder: "... write here ..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **Security Note:** Please do not share sensitive information such as personal data, confidential project details, or sensitive datasets in this report.
