name: "💡 Feature Request"
description: Suggest a new feature or enhancement for excelerate.
title: "💡 [FEAT] - <title>"
labels:
  - "feature"
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
          <img src="https://raw.githubusercontent.com/AmeliaES/excelerate/refs/heads/main/man/figures/logo.png" alt="excelerate Logo">
          <br>
          <em>—<a href="https://ameliaes.github.io/excelerate/">excelerate documentation</a>.</em>
        </p>
  - type: checkboxes
    id: checks
    attributes:
      label: "Before Submitting"
      description: Please confirm the following to help us process your request efficiently.
      options:
        - label: I have checked if this feature already exists or has been requested.
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: "Feature Description"
      description: Please provide a clear and concise description of the feature you are requesting.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: "Proposed Solution"
      description: Describe how you envision this feature working.
      placeholder: "Explain how the feature should function."
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: "Examples or References"
      description: Provide any examples, links, or references that might help illustrate your request.
      placeholder: "Hint: Optional, e.g., screenshots, links to similar features in other projects, etc."
    validations:
      required: false
  - type: dropdown
    id: contribution
    attributes:
      label: "Willing to Contribute?"
      description: Would you be willing to help implement this feature?
      options:
        - "Yes"
        - "No"
  - type: markdown
    attributes:
      value: |
        **Security Note:** Please do not share sensitive information such as personal data, confidential project details, or sensitive datasets in this request.
